format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$line_break\
$character"""

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
read_only = "ğŸ”‘"

[character]
#success_symbol = "[â¯](purple)"
#error_symbol = "[â¯](#FF9900)"
#vimcmd_symbol = "[â®](green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
#style = "bright-black"

#[git_status]
#format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
#style = "cyan"
#conflicted = "â€‹"
#untracked = "â€‹"
#modified = "â€‹"
#staged = "â€‹"
#renamed = "â€‹"
#deleted = "â€‹"
#stashed = "â‰¡"

[git_state]
#format = '\([$state( $progress_current/$progress_total)]($style)\) '
#style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
show_milliseconds = true
#style = "yellow"

[python]
format = "[$virtualenv]($style) "
#style = "bright-black"
